<a href="https://colab.research.google.com/github/elsy-torres/CICESE/blob/main/matriz-regresion02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [114]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import linregress
import random
from decimal import Decimal, getcontext
getcontext().prec = 3

In [20]:
N = 3 #grado del polinomio
M = N + 2

In [21]:
#Usuario debe ingresar los coeficientes separados por en coma en un vector.
coef = [5, 4, 1, 2] # Coeficientes

In [22]:
x = np.arange(0,N)
print(x)

[0 1 2]


In [23]:
c = np.arange(1,M)
m= sorted(c, reverse=True)
print(m)

[4, 3, 2, 1]


In [74]:
a = np.zeros((np.size(x),np.size(m)))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [75]:
 for i in np.arange(0,np.size(m)):
  for j in np.arange(0,np.size(x)):
    a[j,i] = x[j]**(m[i]-1)
  
print(a)

[[0. 0. 0. 1.]
 [1. 1. 1. 1.]
 [8. 4. 2. 1.]]


In [26]:
y = np.matmul(a,coef)
print(y)

[ 2. 12. 60.]


In [28]:
#linregress?

In [29]:
regresion = linregress(x, y)

In [ ]:
x_reg = np.array([x.min(), x.max()])
y_reg = regresion.slope * x_reg + regresion.intercept
plt.scatter(x, y, label="Datos")
plt.plot(x_reg, y_reg, color="C1", label="Regresión Lineal")
plt.show()

In [ ]:
#mi = np.diag(np.arange(0, 20, ))
#print (mi)

In [80]:
mi = np.identity(3)
print(mi)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#mi [mi == 1] = 1/ np.random.rand() # cambiar valores de una matriz diagonal
#print(mi)

In [122]:
s = np.random.rand(N) #incertidumbres
print("s:{0:.2f}".format(s))

TypeError: ignored

In [119]:
Ce = mi * 1/s

['0.42', '0.48', '0.38']

In [88]:
A_prima = np.dot(Ce,a) #Matriz A'
print(A_prima)

[[ 0.          0.          0.          2.52737104]
 [ 1.05143217  1.05143217  1.05143217  1.05143217]
 [10.59138196  5.29569098  2.64784549  1.32392275]]


In [79]:
y_prima = y * 1/s
print(y_prima)

[ 2.22966715 79.56595214 70.82378313]


In [93]:
X_1 = np.dot(np.transpose(A_prima),A_prima)
print(X_1)

[[113.28288149  57.19419555  29.14985259  15.1276811 ]
 [ 57.19419555  29.14985259  15.1276811    8.11659536]
 [ 29.14985259  15.1276811    8.11659536   4.61105249]
 [ 15.1276811    8.11659536   4.61105249   9.24588542]]


In [95]:
X_inv = np.linalg.inv(X_1)
print(X_inv)

[[-2.34562481e+13  7.03687442e+13 -4.69124961e+13  1.92530202e-02]
 [ 7.03687442e+13 -2.11106233e+14  1.40737488e+14  2.05175468e-02]
 [-4.69124961e+13  1.40737488e+14 -9.38249922e+13 -1.96323782e-01]
 [ 2.60922025e-02 -0.00000000e+00 -1.82645418e-01  1.56553215e-01]]


In [97]:
X_2 = np.dot(np.transpose(A_prima),y_prima)
print(X_2)

[833.77994126 458.71907168 271.18863688 183.05861566]


In [99]:
X = np.dot(X_inv,X_2)
print(X)

[ -8.         -32.         104.           0.88220808]
